Repository cameronRomo/silver-nest, pull requests merged in 2021-01, with the labels that each got.

#6 Feature/initial component structure
  .eslintcache
  package-lock.json
  package.json
  src/About/About.js
  src/About/About.scss
  src/About/About.test.js
  src/App.js
  src/App/App.js
  src/App/App.scss
  src/App/App.test.js
  src/Form/Form.js
  src/Form/Form.scss
  src/Form/Form.test.js
  src/GetInvolved/GetInvolved.js
  src/GetInvolved/GetInvolved.scss
  src/GetInvolved/GetInvolved.test.js
  src/NavBar/NavBar.js
  src/NavBar/NavBar.scss
  src/Profile/Profile.js
  src/Profile/Profile.scss
  src/Profile/Profile.test.js
  src/Thumbnails/Thumbnails.css
  src/Thumbnails/Thumbnails.js
  src/Thumbnails/Thumbnails.test.js
  src/index.js
Labels: SCSS/Material-UI

#8 About component
  .eslintcache
  src/About/About.js
  src/App/App.js
  src/App/App.scss
  src/FindARoommate/FindARoommate.js
  src/FindARoommate/FindARoommate.scss
  src/FindARoommate/FindARoommate.test.js
  src/NavBar/NavBar.js
  src/geometric-heart-logo.png
Labels: React Component, SCSS/Material-UI

#14 Find a roomate component
  .eslintcache
  src/App/App.css
  src/App/App.js
  src/FindARoommate/FindARoommate.js
  src/Form/.Form.js.swp
  src/Form/Form.js
  src/NavBar/NavBar.js
  src/Thumbnails/Thumbnails.js
  src/apiCalls.js
Labels: API calls, enhancement

#17 Render residents components
  .eslintcache
  .vscode/launch.json
  package-lock.json
  package.json
  src/About/About.js
  src/About/About.scss
  src/App/App.css
  src/App/App.js
  src/FindARoommate/FindARoommate.js
  src/FindARoommate/FindARoommate.scss
  src/Form/.Form.js.swp
  src/Form/Form.js
  src/Form/Form.scss
  src/NavBar/NavBar.js
  src/NavBar/NavBar.scss
  src/Profile/Profile.js
  src/Profile/Profile.scss
  src/Thumbnails/Thumbnails.css
  src/Thumbnails/Thumbnails.js
  src/apiCalls.js
  src/assets/tileData.js
  src/bothLogos.png
  src/geometric-heart-logo.png
  src/mtnViewLogo.png
  src/silverNestLogo2.png
  src/silverNestLogo3.png
  src/turingHealthLogo.png
  src/turingHeartLogo.png
Labels: API calls, React Component, SCSS/Material-UI

#19 Add framework and set up our README
  README.md
Labels: README

#21 Profile style
  .eslintcache
  package-lock.json
  src/About/About.js
  src/App/App.css
  src/FindARoommate/FindARoommate.js
  src/Form/Form.js
  src/Profile/Profile.js
  src/Thumbnails/Thumbnails.js
Labels: React Component, SCSS/Material-UI

#26 Testing components
  .eslintcache
  .gitignore
  package.json
  src/FindARoommate/FindARoommate.js
  src/FindARoommate/FindARoommate.test.js
  src/Form/Form.js
  src/Form/Form.test.js
  src/NavBar/NavBar.js
  src/NavBar/NavBar.test.js
  src/mockResidentData.js
Labels: Testing

#27 Iteration 4v2
  .eslintcache
  public/index.html
  src/About/About.js
  src/App/App.css
  src/App/App.js
  src/FindARoommate/FindARoommate.js
  src/Form/Form.js
  src/Profile/Profile.js
  src/Thumbnails/Thumbnails.js
  src/apiCalls.js
  src/bothLogos.png
  src/mtnViewLogo.png
  src/silverNestLogo2.png
  src/turingHeartLogo.png
Labels: React Component, SCSS/Material-UI

#28 Testing components 2
  .gitignore
  src/About/About.test.js
  src/App/App.js
  src/FindARoommate/FindARoommate.js
  src/FindARoommate/FindARoommate.test.js
  src/Form/Form.js
  src/Form/Form.test.js
  src/Profile/Profile.js
  src/Profile/Profile.test.js
  src/Thumbnails/Thumbnails.js
  src/Thumbnails/Thumbnails.test.js
  src/mockResidentData.js
Labels: Testing, help wanted

#29 Testing components 3
  src/App/App.test.js
  src/FindARoommate/FindARoommate.test.js
  src/Form/Form.test.js
  src/NavBar/NavBar.test.js
  src/Thumbnails/Thumbnails.test.js
Labels: Testing

#31 Persist on apply
  .eslintcache
  package-lock.json
  src/About/About.js
  src/FindARoommate/FindARoommate.js
  src/Form/Form.js
  src/NavBar/NavBar.js
  src/Profile/Profile.js
  src/Thumbnails/Thumbnails.js
Labels: SCSS/Material-UI, enhancement
